# Site settings
title: Roukou Tech Tips
email: tpliakas@gmail.com
description: > # Writer Theme is a responsive template
 focussed on Java and other programming languages. Providing tech tips that I found during my professional work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Author : ['Author', '/author/thomas', 'fa-user']
single_footer: '<p>Thomas Pliakas &copy; 2019 <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
    Writer: ['Thomas Pliakas 2019', '/about']


# Build settings
# markdown: kramdown
