title: Roukou Thoughts
logo: /assets/img/logo.png
description: This blog explores a variety of topics that I’ve stumbled across in my journey as a software developer. Even though mostly written for my own understanding, my hope is that the curious programmer finds my writings entertaining.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
